django_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('home.urls')),
	path('products/', include('products.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'products', views.ProductViewSet)


app_name = 'homepage'

urlpatterns = [
    path('', views.HomeView.as_view(), name="overview"),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

products/urls.py
from django.urls import path
from . import views


app_name = 'products'

urlpatterns = [
    path('', views.ProductsView.as_view(), name="list"),
    path('product/<slug>', views.ProductDetailView.as_view(), name="detail"),
]

home/models.py
from django.db import models

# Create your models here.

class HomeOverview(models.Model):
	""" Placeholder model for the home page. """

	pass

products/models.py
from django.db import models
from datetime import datetime
from django.utils.text import slugify

# Create your models here.

class ProductManager(models.Manager):
	""" Manager for the Products. """

	def get_queryset(self):
		return super(ProductManager, self).get_queryset().all()

class ProductsModel(models.Model):
	""" Model for the Products. """

	name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	slug = models.SlugField(unique=True, blank=True, null=True)
	date_inserted = models.DateTimeField(auto_now_add=True)
	total_sells = models.IntegerField(default=0)


	objects = models.Manager()
	ab_ob = ProductManager()

	def save(self, *args, **kwargs):
		if not self.slug:
			# Get current timestamp
			epoch = datetime.utcfromtimestamp(0)
			the_time = (datetime.utcnow() - epoch).total_seconds()
			slug = f'{slugify(self.name)}-{slugify(the_time)}'
			self.slug = slug

		super().save(*args, **kwargs)

		def __str__(self):
			return f"{self.name}"

	class Meta:
		verbose_name = 'Products'
		verbose_name_plural = 'Product'

home/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.conf import settings
from . import models
import os

from rest_framework import viewsets
from .serializers import ProductSerializer
from products.models import ProductsModel
import json
from django.contrib.staticfiles.storage import staticfiles_storage
from utils import utils

# Create your views here.

class HomeView(ListView):
	""" View for the main page. """

	model = models.HomeOverview
	template_name = 'home/home.html'
	context_object_name = 'general'

	#queryset = ProductsModel.objects.all().order_by('date_inserted')
	

	
	def setup(self, *args, **kwargs):
		super().setup(*args, **kwargs)

		self.context = {}


		products_json = {}
		
		p = os.path.join(settings.STATIC_ROOT, ('assets/json/products.json'))
		with open(p, 'r', encoding="utf-8") as f:
			f = f.read().strip()\
			.replace("'", '"')\
			.replace('datetime.datetime', '"datetime.datetime')\
			.replace(')', ')"')\
			.replace('datetime.date(', '"datetime.date(')\
			.replace(', tzinfo=<UTC>', '')

			products_json = json.loads(f)


			products_json = utils.format_date(products_json)
			products_json = utils.group_products(products_json)
			print(products_json)



		self.context = {
			'all_products': ProductsModel.objects.filter(),
			'endpoint': 'http://localhost:8000',
			'all_products_json': products_json
		}
		
		self.render = render(
			self.request, self.template_name, self.context
		)

	def get(self, *args, **kwargs):
		return self.render

class ProductViewSet(viewsets.ModelViewSet):
	queryset = ProductsModel.objects.all().order_by('date_inserted')
	serializer_class = ProductSerializer
	http_method_names = ['get']

products/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import DetailView

from . import models

# Create your views here.

class ProductsView(ListView):
	""" View for all products. """

	model = models.ProductsModel
	template_name = 'products/list.html'
	context_object_name = 'products'
	ordering = ['date_inserted']


class ProductDetailView(DetailView):
	""" View for a specific product. """

	model = models.ProductsModel
	template_name = 'products/detail.html'
	context_object_name = 'product'
	slug_url_kwarg = 'slug'

home/templates/home/home.html
{% extends 'base.html' %}
{% block extrahead %}
{% block title %}Home | Test{% endblock %}


{% block content %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<div style="text-align: center;">
	Hello, this is the home page!
</div>



<table class="table table-bordered" id="product-table">
	<thead>
		<tr id="consult_date">
			<th scope="col">Produto</th>
			<th scope="col">Data de Inserção na Loja</th>
			<th scope="col">Total de Vendas</th>
			<th scope="col">12 de Janeiro</th>
			<th scope="col">13 de Janeiro</th>
			<th scope="col">14 de Janeiro</th>
			<th scope="col">15 de Janeiro</th>
		</tr>
	</thead>

	{% for product_name, products in all_products_json.items %}
	  <tbody id="products_spec">
	  	
  		<tr>
	  		<th scope="row"><a href="{{product_name}}">{{product_name}}</a></th>
	  		{% for product in products %}
	  			<!--
				<td>{{ product.product_url__created_at|date:'y-m-d' }}&nbsp;&nbsp;</td>-->
				<td>{{ product.c }}</td>


				<!-- This needs to be filtered by Date
				<script type="text/javascript">
					$('#consult_date').append(`
					<th scope="col">{{product.consulte_date|date:'y-m-d'}}</th>`);
				</script>

				-->
			{% endfor %}
		</tr>
	    
	  </tbody>
	
	{% endfor %}

</table>

{% endblock %}
{% endblock %}

products/templates/products/detail.html
{% extends 'base.html' %}


{% block title %}{{ product.name }} | Test Website {% endblock %}

{% block content %}

<div class="text-content" style="text-align: center;">
	<h1 style="word-wrap: break-word;">{{ product.name }}</h1>
    <p>
    {{ product.description }}</p>
	<ul class="list-group">
		<li class="list-group-item">Inserted At • {{ product.date_inserted }}</li>
	</ul>
</div>

{% endblock %}

products/templates/products/list.html
{% extends 'base.html' %}


{% block title %} Products | Test Website {% endblock %}
{% block content %}

	<div class="card-container">
		<div class="flex-box-card-container">
		
			
			{% for product in products %}
				<a href="{% url 'products:detail' product.slug %}">
					<h1>{{product.name}}</h1>
					<p>{{product.description}} | {{product.date_inserted}}</p>
				</a>
			{% endfor %}	
		</div>
		
	</div>
	

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
	{% include 'partials/_head.html' %}
	<title>{% block title %}{% endblock %}The Language Sloth</title>
</head>
<body>
	{% include 'partials/_nav.html' %}

    {% block content %}{% endblock %}

    {% include 'partials/_footer.html' %}
</body>
</html>

templates/partials/_footer.html
{% load static %}


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% block javascript %}{% endblock javascript%}

templates/partials/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device.width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">

templates/partials/_nav.html
{% load static %}